AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Tokenization Example

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
        Handler: tokenize
        CodeUri: /tokenize.zip
        Runtime: go1.x
  Function:
    Type: AWS::Serverless::Function
    Properties:
        Handler: detokenize
        CodeUri: /detokenize.zip
        Runtime: go1.x
  Function:
    Type: AWS::Serverless::Function
    Properties:
        Handler: rotate_keys
        CodeUri: /rotate_keys.zip
        Runtime: go1.x
  Function:
    Type: AWS::Serverless::Function
    Properties:
        Handler: evolve_policy
        CodeUri: /evolve_policy.zip
        Runtime: go1.x
