AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Tokenization Example
Resources:
  Detokenizer:
    Properties:
      CodeUri: s3://aws-serverless-tokenization/a055cf8b0a8be51d1cfb23be7a6e196e
      Events:
        Detokenize:
          Properties:
            Method: post
            Path: /detokenize
          Type: Api
      Handler: cmd/detokenize/main
      Runtime: go1.x
    Type: AWS::Serverless::Function
  EncryptionKeyRotator:
    Properties:
      CodeUri: s3://aws-serverless-tokenization/a055cf8b0a8be51d1cfb23be7a6e196e
      Events:
        Rotate:
          Properties:
            Pattern:
              Detail:
                DocumentName:
                - EncryptionKeyRotatorDocument
              DetailType:
              - EC2 Command Status-change Notification
              Source:
              - aws.ssm
          Type: CloudWatchEvent
      Handler: cmd/rotate_encryption_key/main
      Runtime: go1.x
    Type: AWS::Serverless::Function
  EncryptionKeyRotatorDocument:
    Properties:
      Content:
        Fn::Sub: "{\n  \"schemaVersion\": \"0.3\",\n  \"parameters\": {\n      \"\
          IsReplace\": {\n          \"type\": \"String\",\n          \"default\":\
          \ \"false\"\n      },\n      \"EncryptionKeyID\": {\n          \"type\"\
          : \"String\",\n          \"default\": \"\"\n      }\n  },\n  \"mainSteps\"\
          : [{\n      \"name\": \"InvokeEncryptionKeyRotator\",\n      \"action\"\
          : \"aws:invokeLambdaFunction\",\n      \"inputs\": {\n          \"FunctionName\"\
          : \"${EncryptionKeyRotator}\",\n          \"Payload\": \"{\\\"IsReplace\\\
          \": \\\"{{IsReplace}}\\\", \\\"EncryptionKeyID\\\": \\\"{{EncryptionKeyID}}\\\
          \"}\"\n      }\n  }]\n}\n"
      DocumentType: Automation
    Type: AWS::SSM::Document
  EncryptionKeys:
    Properties:
      AttributeDefinitions:
      - AttributeName: EncryptionKeyID
        AttributeType: S
      KeySchema:
      - AttributeName: EncryptionKeyID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      TableName: EncryptionKeys
    Type: AWS::DynamoDB::Table
  PolicyKeyEvolver:
    Properties:
      CodeUri: s3://aws-serverless-tokenization/a055cf8b0a8be51d1cfb23be7a6e196e
      Events:
        Evolve:
          Properties:
            Pattern:
              Detail:
                DocumentName:
                - PolicyKeyEvolverDocument
              DetailType:
              - EC2 Command Status-change Notification
              Source:
              - aws.ssm
          Type: CloudWatchEvent
      Handler: cmd/evolve_policy_key/main
      Policies:
      - kms:Create*
      - kms:GenerateDataKey*
      - dynamodb:PutItem
      Runtime: go1.x
    Type: AWS::Serverless::Function
  PolicyKeyEvolverDocument:
    Properties:
      Content:
        Fn::Sub: "{\n  \"schemaVersion\": \"0.3\",\n  \"mainSteps\": [{\n      \"\
          name\": \"InvokePolicyKeyEvolver\",\n      \"action\": \"aws:invokeLambdaFunction\"\
          ,\n      \"inputs\": {\n          \"FunctionName\": \"${PolicyKeyEvolver}\"\
          \n      }\n  }]\n}\n"
      DocumentType: Automation
    Type: AWS::SSM::Document
  PolicyKeys:
    Properties:
      AttributeDefinitions:
      - AttributeName: PolicyKeyID
        AttributeType: S
      KeySchema:
      - AttributeName: PolicyKeyID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      TableName: PolicyKeys
    Type: AWS::DynamoDB::Table
  Tokenizer:
    Properties:
      CodeUri: s3://aws-serverless-tokenization/a055cf8b0a8be51d1cfb23be7a6e196e
      Events:
        Tokenize:
          Properties:
            Method: post
            Path: /tokenize
          Type: Api
      Handler: cmd/tokenize/main
      Runtime: go1.x
    Type: AWS::Serverless::Function
  Tokens:
    Properties:
      AttributeDefinitions:
      - AttributeName: Token
        AttributeType: S
      KeySchema:
      - AttributeName: Token
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      TableName: Tokens
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
