AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Tokenization Example

Resources:
  # DynamoDB Tables
  EncryptionKeys:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: EncryptionKeyId
          AttributeType: S
        # - AttributeName: DataKey
        #   AttributeType: Binary
        # - AttributeName: IsCurrent
        #   AttributeType: BOOL
        # - AttributeName: RotatedAt
        #   AttributeType: S
      KeySchema:
        - AttributeName: EncryptionKeyId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: EncryptionKeys
      SSESpecification:
        SSEEnabled: true

  PolicyKeys:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PolicyKeyId
          AttributeType: S
        # - AttributeName: DataKey
        #   AttributeType: Binary
        # - AttributeName: CreatedAt
        #   AttributeType: S
      KeySchema:
        - AttributeName: PolicyKeyId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: PolicyKeys
      SSESpecification:
        SSEEnabled: true

  Tokens:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Token
          AttributeType: S
        # - AttributeName: PolicyKeyId
        #   AttributeType: S
        # - AttributeName: EncryptionKeyId
        #   AttributeType: S
        # - AttributeName: Pan
        #   AttributeType: S
      KeySchema:
        - AttributeName: Token
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: Tokens
      SSESpecification:
        SSEEnabled: true

  # Lambda Functions
  Tokenizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cmd/tokenize/tokenize
      Runtime: go1.x
      Events:
        Tokenize:
          Type: Api
          Properties:
            Path: /tokenize
            Method: post

  Detokenizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cmd/detokenize/detokenize
      Runtime: go1.x
      Events:
        Detokenize:
          Type: Api
          Properties:
            Path: /detokenize
            Method: post

  EncryptionKeyRotator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cmd/rotate_encryption_key/rotate_encryption_key
      Runtime: go1.x
      Events:
        Rotate:
          Type: CloudWatchEvent
          Properties:
            Pattern:

  PolicyKeyEvolver:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cmd/evolve_policy_key/evolve_policy_key
      Runtime: go1.x
      Events:
        Evolve:
          Type: CloudWatchEvent
          Properties:
            Pattern:
