AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Tokenization Example
Resources:
  Detokenizer:
    Properties:
      CodeUri: s3://aws-serverless-tokenization/a8452801ddfd7df7d9666b0bbe4d2431
      Events:
        Detokenize:
          Properties:
            Method: post
            Path: /detokenize
          Type: Api
      Handler: cmd/detokenize/main
      Runtime: go1.x
    Type: AWS::Serverless::Function
  EncryptionKeyRotator:
    Properties:
      CodeUri: s3://aws-serverless-tokenization/a8452801ddfd7df7d9666b0bbe4d2431
      Handler: cmd/rotate_encryption_key/main
      Policies:
      - Statement:
        - Action:
          - kms:GenerateDataKey
          - kms:CreateKey
          Effect: Allow
          Resource: '*'
        Version: 2012-10-17
      - AmazonDynamoDBFullAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  EncryptionKeys:
    Properties:
      AttributeDefinitions:
      - AttributeName: EncryptionKeyID
        AttributeType: S
      KeySchema:
      - AttributeName: EncryptionKeyID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      TableName: EncryptionKeys
    Type: AWS::DynamoDB::Table
  PolicyKeyEvolver:
    Properties:
      CodeUri: s3://aws-serverless-tokenization/a8452801ddfd7df7d9666b0bbe4d2431
      Handler: cmd/evolve_policy_key/main
      Policies:
      - Statement:
        - Action:
          - kms:GenerateDataKey
          - kms:CreateKey
          Effect: Allow
          Resource: '*'
        Version: 2012-10-17
      - AmazonDynamoDBFullAccess
      Runtime: go1.x
    Type: AWS::Serverless::Function
  PolicyKeys:
    Properties:
      AttributeDefinitions:
      - AttributeName: PolicyKeyID
        AttributeType: S
      KeySchema:
      - AttributeName: PolicyKeyID
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      TableName: PolicyKeys
    Type: AWS::DynamoDB::Table
  Tokenizer:
    Properties:
      CodeUri: s3://aws-serverless-tokenization/a8452801ddfd7df7d9666b0bbe4d2431
      Events:
        Tokenize:
          Properties:
            Method: post
            Path: /tokenize
          Type: Api
      Handler: cmd/tokenize/main
      Runtime: go1.x
    Type: AWS::Serverless::Function
  Tokens:
    Properties:
      AttributeDefinitions:
      - AttributeName: Token
        AttributeType: S
      KeySchema:
      - AttributeName: Token
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      TableName: Tokens
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
